### ISSUE TITLE
Single click opens both registered app and rename popup.

### ISSUE THREAD

**Issue by klricks** [raspberrypi-ui/pcmanfm#2]
When **single click** is configured in preferences and **detailed view** is selected then clicking on a file will always open both the registered app AND the rename popup at the same time. 

When any of the other icon view settings are selected, then clicking on the title field associated with the icon also launches the app AND rename box at the same time.  In this case clicking on the icon will open only the registered app as expected.

See: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=211065

**Comment by spl237** [comment]
OK, the easiest thing to do is to remove the click to rename behaviour if in single-click mode; I've patched the code to do that. The fix should be available from apt in the next day or so.

Many thanks for the report.
